### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by 1621391916** [lingsamuel/EpicGamesGiveawaysAutoClaimer#10]
![image](https://user-images.githubusercontent.com/42343279/83960789-6c744300-a8bf-11ea-9783-ec1ddd1e1522.png)
按照教程做了下来，点了star就这样了。
不知道哪里出错了

**Comment by lingsamuel** [comment]
最近Epic更改了系统，本脚本暂时已无法正常运行。原作者的更新还没上线。

**Comment by lingsamuel** [comment]
讨论移步 https://github.com/lingsamuel/EpicGamesGiveawaysAutoClaimer/issues/11#issuecomment-673864371
