### ISSUE TITLE
这样报错正常吗？是不是因为本周领过了……

### ISSUE THREAD

**Issue by RtYkk** [lingsamuel/EpicGamesGiveawaysAutoClaimer#8]
[https://github.com/RtYkk/EpicGamesGiveawaysAutoClaimer/actions/runs/106983962](https://github.com/RtYkk/EpicGamesGiveawaysAutoClaimer/actions/runs/106983962)

**Comment by RtYkk** [comment]
好像是正常的，先close了，我看您也有一样的问题。谢谢，我就怕是我自己配置错了…

**Comment by lingsamuel** [comment]
可能是 github 执行 actions 使用的 ip 问题，引发了 epic 的保护机制。建议修改脚本的执行时间，避免扎堆执行。
